# Generated by Django 4.2.7 on 2023-11-24 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DietApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athletedata',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='athletedata',
            name='body_temp',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='athletedata',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='athletedata',
            name='duration',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='athletedata',
            name='gender',
            field=models.PositiveIntegerField(choices=[(0, 'Female'), (1, 'Male')], default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='athletedata',
            name='heart_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='athletedata',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='athletedata',
            name='prediction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athletedata',
            name='weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='athletedata',
            name='age',
            field=models.PositiveIntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(40)]),
        ),
    ]
