# Generated by Django 4.2.7 on 2023-11-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DietApp', '0002_alter_athletedata_options_athletedata_body_temp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=255)),
                ('img_url', models.CharField(max_length=255)),
                ('carbohydrates', models.PositiveIntegerField()),
                ('fat', models.PositiveIntegerField()),
                ('protein', models.PositiveIntegerField()),
                ('Calories', models.FloatField()),
            ],
        ),
    ]
